import { cn } from "@/lib/cn";
import { SYMBOL, WORDMARK } from "./orchestr-paths";

/**
 * Orchestr identity. Symbol: three sections of an orchestra (arcs) around the conductor
 * (centre node). Geometry and wordmark outlines are generated by scripts/build-brand-logo.mjs.
 */
function SymbolShapes({ stroke, dot }: { stroke: string; dot: string }) {
  return (
    <>
      <g fill="none" stroke={stroke} strokeWidth={SYMBOL.stroke} strokeLinecap="round">
        {SYMBOL.arcs.map((d) => (
          <path key={d} d={d} />
        ))}
      </g>
      <circle cx={SYMBOL.dot.cx} cy={SYMBOL.dot.cy} r={SYMBOL.dot.r} fill={dot} />
    </>
  );
}

function Gradient({ id }: { id: string }) {
  return (
    <defs>
      <linearGradient id={id} x1="4" y1="6" x2="30" y2="26" gradientUnits="userSpaceOnUse">
        <stop offset="0" stopColor="#B6F7DD" />
        <stop offset="0.55" stopColor="#3DE0A0" />
        <stop offset="1" stopColor="#7C8BFF" />
      </linearGradient>
    </defs>
  );
}

type Tone = "on-dark" | "on-light";

/** Symbol only. */
export function OrchestrMark({
  tone = "on-dark",
  className,
  id = "orx-mark",
}: {
  tone?: Tone;
  className?: string;
  id?: string;
}) {
  const dark = tone === "on-dark";
  return (
    <svg viewBox="0 0 32 32" className={cn("size-8 shrink-0", className)} aria-hidden>
      {dark && <Gradient id={id} />}
      <SymbolShapes stroke={dark ? `url(#${id})` : "#07090B"} dot={dark ? "#3DE0A0" : "#13935F"} />
    </svg>
  );
}

/** Symbol + wordmark lockup. Height drives size; width follows. */
export function OrchestrLogo({
  tone = "on-dark",
  className,
  id = "orx-logo",
  title,
}: {
  tone?: Tone;
  className?: string;
  id?: string;
  /** Accessible name; omit when a parent link already names it. */
  title?: string;
}) {
  const dark = tone === "on-dark";
  return (
    <svg
      viewBox={`0 0 ${WORDMARK.width} 32`}
      className={cn("h-7 w-auto shrink-0", className)}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : true}
      aria-label={title}
    >
      {dark && <Gradient id={id} />}
      <SymbolShapes stroke={dark ? `url(#${id})` : "#07090B"} dot={dark ? "#3DE0A0" : "#13935F"} />
      <path
        transform={`translate(${WORDMARK.x} ${WORDMARK.baseline})`}
        fill={dark ? "#F2F5F4" : "#07090B"}
        d={WORDMARK.d}
      />
    </svg>
  );
}
