import {
  Bot,
  Calculator,
  Clock,
  Database,
  FileText,
  GitFork,
  Globe,
  Hourglass,
  Receipt,
  Repeat,
} from "lucide-react";
import type { Flow } from "./types";

/* Core-node glyph colours, picked to sit next to the official brand logos. */
const ACCENT = "#2b5bff";
const AMBER = "#d98a12";
const ROSE = "#e5484d";
const INK = "#3a414b";

const agent = { glyph: Bot, tone: ACCENT };
const branch = { glyph: GitFork, tone: ACCENT };
const memory = { glyph: Database, tone: INK };

export const FLOWS: Flow[] = [
  {
    id: "marcacoes",
    tab: "Marcações",
    mark: "whatsapp",
    name: "Cabeleireiro · Marcações por WhatsApp",
    before: "Alguém responde a cada mensagem, consulta a agenda à mão e esquece-se dos lembretes.",
    after:
      "A marcação fica feita em segundos, a confirmação sai logo e o lembrete segue na véspera.",
    saving: "6 h por semana",
    runtime: "2,1 s",
    nodes: [
      {
        id: "t",
        kind: "trigger",
        x: 100,
        y: 200,
        icon: "whatsapp",
        app: "WhatsApp",
        title: "Nova mensagem",
        output: "«Olá! Dá para marcar um corte amanhã ao fim da tarde?»",
      },
      {
        id: "ag",
        kind: "agent",
        x: 350,
        y: 200,
        icon: agent,
        app: "Agente de IA",
        title: "Percebe o pedido",
        output: "Marcação · amanhã, entre as 17h e as 19h",
        subs: [
          { icon: "claude", label: "Modelo" },
          { icon: memory, label: "Memória" },
          { icon: "googleCalendar", label: "Ver agenda" },
        ],
      },
      {
        id: "cal",
        kind: "action",
        x: 590,
        y: 200,
        icon: "googleCalendar",
        app: "Google Calendar",
        title: "Criar evento",
        output: "Qui, 18:00 · Corte · Ana Costa",
        bubble: "bottom",
      },
      {
        id: "wa",
        kind: "action",
        x: 790,
        y: 120,
        icon: "whatsapp",
        app: "WhatsApp",
        title: "Enviar confirmação",
        output: "«Fica marcado: quinta às 18:00. Até lá!»",
      },
      {
        id: "wt",
        kind: "action",
        x: 790,
        y: 290,
        icon: { glyph: Hourglass, tone: AMBER },
        app: "Esperar",
        title: "Até à véspera, 10h",
      },
      {
        id: "wa2",
        kind: "action",
        x: 940,
        y: 290,
        icon: "whatsapp",
        app: "WhatsApp",
        title: "Lembrete",
        output: "«Lembrete: amanhã às 18:00.»",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "t", to: "ag" },
      { from: "ag", to: "cal" },
      { from: "cal", to: "wa" },
      { from: "cal", to: "wt" },
      { from: "wt", to: "wa2" },
    ],
    order: ["t", "ag", "cal", "wa", "wt", "wa2"],
  },
  {
    id: "orcamentos",
    tab: "Orçamentos",
    mark: "gmail",
    name: "Climatização · Orçamentos por email",
    before: "Os pedidos esperam dias numa caixa de email até alguém ter tempo de fazer as contas.",
    after:
      "O orçamento sai com os preços da empresa, em PDF, depois de uma aprovação com um clique.",
    saving: "8 h por semana",
    runtime: "3,4 s",
    nodes: [
      {
        id: "t",
        kind: "trigger",
        x: 100,
        y: 200,
        icon: "gmail",
        app: "Gmail",
        title: "Novo pedido",
        output: "«Orçamento para instalar 2 ares condicionados em Matosinhos»",
      },
      {
        id: "ag",
        kind: "agent",
        x: 350,
        y: 200,
        icon: agent,
        app: "Agente de IA",
        title: "Prepara o orçamento",
        output: "2 instalações + deslocação: 585,00 € + IVA",
        subs: [
          { icon: "claude", label: "Modelo" },
          { icon: "googleSheets", label: "Tabela de preços" },
          { icon: { glyph: Calculator, tone: INK }, label: "Calculadora" },
        ],
      },
      {
        id: "pdf",
        kind: "action",
        x: 590,
        y: 200,
        icon: { glyph: FileText, tone: ROSE },
        app: "Documento",
        title: "Gerar PDF",
        output: "ORC-0142.pdf · 719,55 € com IVA",
        bubble: "bottom",
      },
      {
        id: "apr",
        kind: "action",
        x: 770,
        y: 200,
        icon: "slack",
        app: "Slack",
        title: "Pedir aprovação",
        output: "Aprovado por Rui, 2 minutos depois",
      },
      {
        id: "send",
        kind: "action",
        x: 940,
        y: 200,
        icon: "gmail",
        app: "Gmail",
        title: "Enviar ao cliente",
        output: "Enviado com o PDF em anexo",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "t", to: "ag" },
      { from: "ag", to: "pdf" },
      { from: "pdf", to: "apr" },
      { from: "apr", to: "send" },
    ],
    order: ["t", "ag", "pdf", "apr", "send"],
  },
  {
    id: "fornecedores",
    tab: "Faturas de fornecedores",
    mark: "outlook",
    name: "Distribuição · Faturas de fornecedores",
    before:
      "Os PDF ficam perdidos no email, são copiados à mão para o Excel e chegam tarde ao contabilista.",
    after: "Cada fatura é lida, arquivada e registada sozinha. As grandes pedem aprovação antes.",
    saving: "5 h por semana",
    runtime: "2,8 s",
    nodes: [
      {
        id: "t",
        kind: "trigger",
        x: 100,
        y: 200,
        icon: "outlook",
        app: "Outlook",
        title: "Email com fatura",
        output: "Frio Total · FT 2026/1843.pdf",
      },
      {
        id: "ler",
        kind: "action",
        x: 270,
        y: 200,
        icon: "claude",
        app: "Claude",
        title: "Ler a fatura",
        output: "Frio Total · 312,40 € · vence a 31/10",
        bubble: "bottom",
      },
      {
        id: "if",
        kind: "logic",
        x: 450,
        y: 200,
        icon: branch,
        app: "Condição",
        title: "Acima de 500 €?",
      },
      {
        id: "apr",
        kind: "action",
        x: 640,
        y: 120,
        icon: "teams",
        app: "Microsoft Teams",
        title: "Pedir aprovação",
      },
      {
        id: "drv",
        kind: "action",
        x: 640,
        y: 290,
        icon: "googleDrive",
        app: "Google Drive",
        title: "Arquivar o PDF",
        output: "Fornecedores / 2026 / 10",
        bubble: "bottom",
      },
      {
        id: "xl",
        kind: "action",
        x: 840,
        y: 200,
        icon: "excel",
        app: "Excel",
        title: "Registar despesa",
        output: "Linha 214: Frio Total, 312,40 €",
      },
    ],
    edges: [
      { from: "t", to: "ler" },
      { from: "ler", to: "if" },
      { from: "if", to: "apr", port: "yes" },
      { from: "if", to: "drv", port: "no", items: "1 item" },
      { from: "apr", to: "xl" },
      { from: "drv", to: "xl" },
    ],
    order: ["t", "ler", "if", "drv", "xl"],
  },
  {
    id: "cobrancas",
    tab: "Cobranças",
    mark: "whatsapp",
    name: "Serviços · Cobranças em atraso",
    before: "Ninguém tem tempo para ver quem deve. As faturas em atraso acumulam-se durante meses.",
    after:
      "Todas as manhãs, cada fatura em atraso recebe o lembrete certo, do mais cordial ao formal.",
    saving: "4 h por semana",
    runtime: "4,2 s",
    nodes: [
      {
        id: "t",
        kind: "trigger",
        x: 90,
        y: 200,
        icon: { glyph: Clock, tone: AMBER },
        app: "Agendamento",
        title: "Todos os dias, 9h",
      },
      {
        id: "inv",
        kind: "action",
        x: 250,
        y: 200,
        icon: { glyph: Receipt, tone: ACCENT },
        app: "Faturação",
        title: "Faturas vencidas",
        output: "3 faturas em atraso · 1.245,60 €",
      },
      {
        id: "loop",
        kind: "action",
        x: 410,
        y: 200,
        icon: { glyph: Repeat, tone: INK },
        app: "Para cada",
        title: "Uma de cada vez",
      },
      {
        id: "if",
        kind: "logic",
        x: 570,
        y: 200,
        icon: branch,
        app: "Condição",
        title: "Mais de 15 dias?",
      },
      {
        id: "gm",
        kind: "action",
        x: 750,
        y: 120,
        icon: "gmail",
        app: "Gmail",
        title: "Aviso formal",
        output: "FT 108 · 40 dias em atraso · aviso enviado",
      },
      {
        id: "wa",
        kind: "action",
        x: 750,
        y: 290,
        icon: "whatsapp",
        app: "WhatsApp",
        title: "Lembrete cordial",
        output: "«A fatura FT 115 venceu há 5 dias. Segue a referência MB.»",
        bubble: "bottom",
      },
      {
        id: "sh",
        kind: "action",
        x: 930,
        y: 200,
        icon: "googleSheets",
        app: "Google Sheets",
        title: "Registar contacto",
        output: "3 cobranças registadas",
      },
    ],
    edges: [
      { from: "t", to: "inv" },
      { from: "inv", to: "loop", items: "3 itens" },
      { from: "loop", to: "if" },
      { from: "if", to: "gm", port: "yes", items: "1 item" },
      { from: "if", to: "wa", port: "no", items: "2 itens" },
      { from: "gm", to: "sh" },
      { from: "wa", to: "sh" },
    ],
    order: ["t", "inv", "loop", "if", "gm", "wa", "sh"],
  },
  {
    id: "contactos",
    tab: "Contactos do site",
    mark: "googleForms",
    name: "Consultoria · Contactos do site",
    before: "Os contactos do site ficam num email que alguém vê ao fim do dia. Os bons arrefecem.",
    after: "Cada contacto é qualificado, entra no CRM e recebe logo um convite para reunião.",
    saving: "3 h por semana",
    runtime: "3,0 s",
    nodes: [
      {
        id: "t",
        kind: "trigger",
        x: 100,
        y: 200,
        icon: "googleForms",
        app: "Formulário do site",
        title: "Novo contacto",
        output: "Rui Matos, Clínica Sorriso: «quero automatizar marcações»",
      },
      {
        id: "ag",
        kind: "agent",
        x: 350,
        y: 200,
        icon: agent,
        app: "Agente de IA",
        title: "Qualifica o contacto",
        output: "Contacto quente · clínica com 4 médicos",
        subs: [
          { icon: "claude", label: "Modelo" },
          { icon: { glyph: Globe, tone: INK }, label: "Pesquisa web" },
          { icon: memory, label: "Memória" },
        ],
      },
      {
        id: "crm",
        kind: "action",
        x: 590,
        y: 200,
        icon: "pipedrive",
        app: "Pipedrive",
        title: "Criar negócio",
        output: "Clínica Sorriso · estimativa 1.200 €",
        bubble: "bottom",
      },
      {
        id: "sl",
        kind: "action",
        x: 790,
        y: 120,
        icon: "slack",
        app: "Slack",
        title: "Avisar o comercial",
        output: "#vendas: novo contacto quente, Clínica Sorriso",
      },
      {
        id: "cal",
        kind: "action",
        x: 790,
        y: 290,
        icon: "calendly",
        app: "Calendly",
        title: "Convite para reunião",
        output: "Reunião marcada: terça, 10:30",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "t", to: "ag" },
      { from: "ag", to: "crm" },
      { from: "crm", to: "sl" },
      { from: "crm", to: "cal" },
    ],
    order: ["t", "ag", "crm", "sl", "cal"],
  },
  {
    id: "encomendas",
    tab: "Encomendas online",
    mark: "shopify",
    name: "Loja online · Encomendas e stock",
    before:
      "Cada encomenda obriga a faturar à mão, enviar a fatura e atualizar o stock numa folha.",
    after:
      "A fatura sai e segue para o cliente sozinha, o stock atualiza-se e avisa antes de acabar.",
    saving: "7 h por semana",
    runtime: "2,6 s",
    nodes: [
      {
        id: "t",
        kind: "trigger",
        x: 100,
        y: 200,
        icon: "shopify",
        app: "Shopify",
        title: "Nova encomenda",
        output: "#1042 · 3 artigos · 89,70 €",
      },
      {
        id: "fat",
        kind: "action",
        x: 270,
        y: 200,
        icon: { glyph: Receipt, tone: ACCENT },
        app: "Faturação",
        title: "Emitir fatura-recibo",
        output: "FR 2026/388 emitida",
        bubble: "bottom",
      },
      {
        id: "gm",
        kind: "action",
        x: 440,
        y: 200,
        icon: "gmail",
        app: "Gmail",
        title: "Enviar ao cliente",
        output: "Fatura enviada a ana.c@…",
      },
      {
        id: "st",
        kind: "action",
        x: 610,
        y: 200,
        icon: "googleSheets",
        app: "Google Sheets",
        title: "Atualizar stock",
        output: "Vela de soja: restam 4",
        bubble: "bottom",
      },
      {
        id: "if",
        kind: "logic",
        x: 780,
        y: 200,
        icon: branch,
        app: "Condição",
        title: "Stock abaixo de 5?",
      },
      {
        id: "sl",
        kind: "action",
        x: 940,
        y: 120,
        icon: "slack",
        app: "Slack",
        title: "Alerta de stock",
        output: "Repor: vela de soja (4 unidades)",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "t", to: "fat" },
      { from: "fat", to: "gm" },
      { from: "gm", to: "st" },
      { from: "st", to: "if" },
      { from: "if", to: "sl", port: "yes", items: "1 item" },
    ],
    order: ["t", "fat", "gm", "st", "if", "sl"],
  },
];

/** How long each kind of node "runs" in the preview, in ms. */
export const RUN_MS = { trigger: 1100, action: 1300, logic: 950, agent: 1900 } as const;
