import { Clock, FileText, Receipt } from "lucide-react";
import type { Flow } from "./types";

export type HeroFlowData = Pick<
  Flow,
  "id" | "tab" | "mark" | "name" | "runtime" | "stage" | "nodes" | "edges" | "order"
>;

/* Four short flows drawn for the hero's narrow frame: one row, outputs alternating above and
   below so neighbouring bubbles never overlap. */
const STAGE = [600, 360] as const;
const X = [70, 220, 370, 520] as const;
const Y = 180;

export const HERO_FLOWS: HeroFlowData[] = [
  {
    id: "marcacoes",
    tab: "Marcações",
    mark: "whatsapp",
    name: "Marcações por WhatsApp",
    runtime: "2,1 s",
    stage: STAGE,
    nodes: [
      {
        id: "a",
        kind: "trigger",
        x: X[0],
        y: Y,
        icon: "whatsapp",
        app: "WhatsApp",
        title: "Nova mensagem",
        output: "«Dá para marcar amanhã às 18h?»",
      },
      {
        id: "b",
        kind: "action",
        x: X[1],
        y: Y,
        icon: "claude",
        app: "Claude",
        title: "Percebe o pedido",
        output: "Marcação · amanhã, 18:00",
        bubble: "bottom",
      },
      {
        id: "c",
        kind: "action",
        x: X[2],
        y: Y,
        icon: "googleCalendar",
        app: "Google Calendar",
        title: "Criar evento",
        output: "Qui, 18:00 · Ana Costa",
      },
      {
        id: "d",
        kind: "action",
        x: X[3],
        y: Y,
        icon: "whatsapp",
        app: "WhatsApp",
        title: "Confirmar",
        output: "«Fica marcado. Até quinta!»",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "a", to: "b" },
      { from: "b", to: "c" },
      { from: "c", to: "d" },
    ],
    order: ["a", "b", "c", "d"],
  },
  {
    id: "orcamentos",
    tab: "Orçamentos",
    mark: "gmail",
    name: "Orçamentos por email",
    runtime: "3,4 s",
    stage: STAGE,
    nodes: [
      {
        id: "a",
        kind: "trigger",
        x: X[0],
        y: Y,
        icon: "gmail",
        app: "Gmail",
        title: "Novo pedido",
        output: "«Orçamento para 2 ares condicionados»",
      },
      {
        id: "b",
        kind: "action",
        x: X[1],
        y: Y,
        icon: "claude",
        app: "Claude",
        title: "Calcula o valor",
        output: "585,00 € + IVA",
        bubble: "bottom",
      },
      {
        id: "c",
        kind: "action",
        x: X[2],
        y: Y,
        icon: { glyph: FileText, tone: "#e5484d" },
        app: "Documento",
        title: "Gerar PDF",
        output: "ORC-0142.pdf · 719,55 €",
      },
      {
        id: "d",
        kind: "action",
        x: X[3],
        y: Y,
        icon: "gmail",
        app: "Gmail",
        title: "Enviar",
        output: "Enviado 4 min depois do pedido",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "a", to: "b" },
      { from: "b", to: "c" },
      { from: "c", to: "d" },
    ],
    order: ["a", "b", "c", "d"],
  },
  {
    id: "fornecedores",
    tab: "Faturas",
    mark: "outlook",
    name: "Faturas de fornecedores",
    runtime: "2,8 s",
    stage: STAGE,
    nodes: [
      {
        id: "a",
        kind: "trigger",
        x: X[0],
        y: Y,
        icon: "outlook",
        app: "Outlook",
        title: "Email com fatura",
        output: "FT 2026/1843.pdf",
      },
      {
        id: "b",
        kind: "action",
        x: X[1],
        y: Y,
        icon: "claude",
        app: "Claude",
        title: "Ler a fatura",
        output: "Frio Total · 312,40 €",
        bubble: "bottom",
      },
      {
        id: "c",
        kind: "action",
        x: X[2],
        y: Y,
        icon: "googleDrive",
        app: "Google Drive",
        title: "Arquivar PDF",
        output: "Fornecedores / 2026 / 10",
      },
      {
        id: "d",
        kind: "action",
        x: X[3],
        y: Y,
        icon: "excel",
        app: "Excel",
        title: "Registar despesa",
        output: "Linha 214 adicionada",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "a", to: "b" },
      { from: "b", to: "c" },
      { from: "c", to: "d" },
    ],
    order: ["a", "b", "c", "d"],
  },
  {
    id: "cobrancas",
    tab: "Cobranças",
    mark: "googleSheets",
    name: "Cobranças em atraso",
    runtime: "3,1 s",
    stage: STAGE,
    nodes: [
      {
        id: "a",
        kind: "trigger",
        x: X[0],
        y: Y,
        icon: { glyph: Clock, tone: "#d98a12" },
        app: "Agendamento",
        title: "Todos os dias, 9h",
      },
      {
        id: "b",
        kind: "action",
        x: X[1],
        y: Y,
        icon: { glyph: Receipt, tone: "#2b5bff" },
        app: "Faturação",
        title: "Faturas vencidas",
        output: "3 em atraso · 1.245,60 €",
        bubble: "bottom",
      },
      {
        id: "c",
        kind: "action",
        x: X[2],
        y: Y,
        icon: "whatsapp",
        app: "WhatsApp",
        title: "Lembrete",
        output: "«A FT 115 venceu há 5 dias.»",
      },
      {
        id: "d",
        kind: "action",
        x: X[3],
        y: Y,
        icon: "googleSheets",
        app: "Google Sheets",
        title: "Registar",
        output: "3 cobranças registadas",
        bubble: "bottom",
      },
    ],
    edges: [
      { from: "a", to: "b", items: "3 itens" },
      { from: "b", to: "c" },
      { from: "c", to: "d" },
    ],
    order: ["a", "b", "c", "d"],
  },
];
